service: lambda-contact # NOTE: update this with your service name
plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  region: us-west-2
  runtime: nodejs6.10
  iamRoleStatements:
    -  Effect: "Allow"
       Action: 
         - "ses:SendEmail"
         - "ses:SendRawEmail"
       Resource: "*"

functions:
  contact:
    handler: handler.contact
    events:
      - http:
          path: contact
          method: post
          cors: true
    environment:
      SITE: https://github.com/nanoxd/lambda-contact
      TO_EMAIL: to@example.com
      FROM_EMAIL: from@example.com

